import { Surah } from '@/types/quran';

export const ALL_114_SURAHS: Surah[] = [
  { id: 1, name_arabic: 'الفاتحة', name_latin: 'Al-Fatihah', translation_id: 'Pembukaan', total_verses: 7, revelation_type: 'meccan' },
  { id: 2, name_arabic: 'البقرة', name_latin: 'Al-Baqarah', translation_id: 'Sapi Betina', total_verses: 286, revelation_type: 'medinan' },
  { id: 3, name_arabic: 'آل عمران', name_latin: "Ali 'Imran", translation_id: 'Keluarga Imran', total_verses: 200, revelation_type: 'medinan' },
  { id: 4, name_arabic: 'النساء', name_latin: "An-Nisa'", translation_id: 'Wanita', total_verses: 176, revelation_type: 'medinan' },
  { id: 5, name_arabic: 'المائدة', name_latin: "Al-Ma'idah", translation_id: 'Hidangan', total_verses: 120, revelation_type: 'medinan' },
  { id: 6, name_arabic: 'الأنعام', name_latin: "Al-An'am", translation_id: 'Hewan Ternak', total_verses: 165, revelation_type: 'meccan' },
  { id: 7, name_arabic: 'الأعراف', name_latin: "Al-A'raf", translation_id: 'Tempat Tertinggi', total_verses: 206, revelation_type: 'meccan' },
  { id: 8, name_arabic: 'الأنفال', name_latin: 'Al-Anfal', translation_id: 'Rampasan Perang', total_verses: 75, revelation_type: 'medinan' },
  { id: 9, name_arabic: 'التوبة', name_latin: 'At-Tawbah', translation_id: 'Pengampunan', total_verses: 129, revelation_type: 'medinan' },
  { id: 10, name_arabic: 'يونس', name_latin: 'Yunus', translation_id: 'Nabi Yunus', total_verses: 109, revelation_type: 'meccan' },
  { id: 11, name_arabic: 'هود', name_latin: 'Hud', translation_id: 'Nabi Hud', total_verses: 123, revelation_type: 'meccan' },
  { id: 12, name_arabic: 'يوسف', name_latin: 'Yusuf', translation_id: 'Nabi Yusuf', total_verses: 111, revelation_type: 'meccan' },
  { id: 13, name_arabic: 'الرعد', name_latin: "Ar-Ra'd", translation_id: 'Guruh', total_verses: 43, revelation_type: 'medinan' },
  { id: 14, name_arabic: 'إبراهيم', name_latin: 'Ibrahim', translation_id: 'Nabi Ibrahim', total_verses: 52, revelation_type: 'meccan' },
  { id: 15, name_arabic: 'الحجر', name_latin: 'Al-Hijr', translation_id: 'Gunung Batu', total_verses: 99, revelation_type: 'meccan' },
  { id: 16, name_arabic: 'النحل', name_latin: 'An-Nahl', translation_id: 'Lebah', total_verses: 128, revelation_type: 'meccan' },
  { id: 17, name_arabic: 'الإسراء', name_latin: "Al-Isra'", translation_id: 'Perjalanan Malam', total_verses: 111, revelation_type: 'meccan' },
  { id: 18, name_arabic: 'الكهف', name_latin: 'Al-Kahf', translation_id: 'Gua', total_verses: 110, revelation_type: 'meccan' },
  { id: 19, name_arabic: 'مريم', name_latin: 'Maryam', translation_id: 'Maryam', total_verses: 98, revelation_type: 'meccan' },
  { id: 20, name_arabic: 'طه', name_latin: 'Taha', translation_id: 'Taha', total_verses: 135, revelation_type: 'meccan' },
  { id: 21, name_arabic: 'الأنبياء', name_latin: "Al-Anbiya'", translation_id: 'Para Nabi', total_verses: 112, revelation_type: 'meccan' },
  { id: 22, name_arabic: 'الحج', name_latin: 'Al-Hajj', translation_id: 'Haji', total_verses: 78, revelation_type: 'medinan' },
  { id: 23, name_arabic: 'المؤمنون', name_latin: "Al-Mu'minun", translation_id: 'Orang-orang Mukmin', total_verses: 118, revelation_type: 'meccan' },
  { id: 24, name_arabic: 'النور', name_latin: 'An-Nur', translation_id: 'Cahaya', total_verses: 64, revelation_type: 'medinan' },
  { id: 25, name_arabic: 'الفرقان', name_latin: 'Al-Furqan', translation_id: 'Pembeda', total_verses: 77, revelation_type: 'meccan' },
  { id: 26, name_arabic: 'الشعراء', name_latin: "Ash-Shu'ara'", translation_id: 'Para Penyair', total_verses: 227, revelation_type: 'meccan' },
  { id: 27, name_arabic: 'النمل', name_latin: 'An-Naml', translation_id: 'Semut', total_verses: 93, revelation_type: 'meccan' },
  { id: 28, name_arabic: 'القصص', name_latin: 'Al-Qasas', translation_id: 'Kisah-kisah', total_verses: 88, revelation_type: 'meccan' },
  { id: 29, name_arabic: 'العنكبوت', name_latin: "Al-'Ankabut", translation_id: 'Laba-laba', total_verses: 69, revelation_type: 'meccan' },
  { id: 30, name_arabic: 'الروم', name_latin: 'Ar-Rum', translation_id: 'Bangsa Romawi', total_verses: 60, revelation_type: 'meccan' },
  { id: 31, name_arabic: 'لقمان', name_latin: 'Luqman', translation_id: 'Luqman', total_verses: 34, revelation_type: 'meccan' },
  { id: 32, name_arabic: 'السجدة', name_latin: 'As-Sajdah', translation_id: 'Sujud', total_verses: 30, revelation_type: 'meccan' },
  { id: 33, name_arabic: 'الأحزاب', name_latin: 'Al-Ahzab', translation_id: 'Golongan Sekutu', total_verses: 73, revelation_type: 'medinan' },
  { id: 34, name_arabic: 'سبأ', name_latin: "Saba'", translation_id: 'Kaum Saba', total_verses: 54, revelation_type: 'meccan' },
  { id: 35, name_arabic: 'فاطر', name_latin: 'Fatir', translation_id: 'Pencipta', total_verses: 45, revelation_type: 'meccan' },
  { id: 36, name_arabic: 'يس', name_latin: 'Ya-Sin', translation_id: 'Ya Sin', total_verses: 83, revelation_type: 'meccan' },
  { id: 37, name_arabic: 'الصافات', name_latin: 'As-Saffat', translation_id: 'Barisan-barisan', total_verses: 182, revelation_type: 'meccan' },
  { id: 38, name_arabic: 'ص', name_latin: 'Sad', translation_id: 'Sad', total_verses: 88, revelation_type: 'meccan' },
  { id: 39, name_arabic: 'الزمر', name_latin: 'Az-Zumar', translation_id: 'Rombongan', total_verses: 75, revelation_type: 'meccan' },
  { id: 40, name_arabic: 'غافر', name_latin: 'Ghafir', translation_id: 'Maha Pengampun', total_verses: 85, revelation_type: 'meccan' },
  { id: 41, name_arabic: 'فصلت', name_latin: 'Fussilat', translation_id: 'Yang Dijelaskan', total_verses: 54, revelation_type: 'meccan' },
  { id: 42, name_arabic: 'الشورى', name_latin: 'Ash-Shura', translation_id: 'Musyawarah', total_verses: 53, revelation_type: 'meccan' },
  { id: 43, name_arabic: 'الزخرف', name_latin: 'Az-Zukhruf', translation_id: 'Perhiasan', total_verses: 89, revelation_type: 'meccan' },
  { id: 44, name_arabic: 'الدخان', name_latin: 'Ad-Dukhan', translation_id: 'Kabut', total_verses: 59, revelation_type: 'meccan' },
  { id: 45, name_arabic: 'الجاثية', name_latin: 'Al-Jathiyah', translation_id: 'Berlutut', total_verses: 37, revelation_type: 'meccan' },
  { id: 46, name_arabic: 'الأحقاف', name_latin: 'Al-Ahqaf', translation_id: 'Bukit Pasir', total_verses: 35, revelation_type: 'meccan' },
  { id: 47, name_arabic: 'محمد', name_latin: 'Muhammad', translation_id: 'Nabi Muhammad', total_verses: 38, revelation_type: 'medinan' },
  { id: 48, name_arabic: 'الفتح', name_latin: 'Al-Fath', translation_id: 'Kemenangan', total_verses: 29, revelation_type: 'medinan' },
  { id: 49, name_arabic: 'الحجرات', name_latin: 'Al-Hujurat', translation_id: 'Kamar-kamar', total_verses: 18, revelation_type: 'medinan' },
  { id: 50, name_arabic: 'ق', name_latin: 'Qaf', translation_id: 'Qaf', total_verses: 45, revelation_type: 'meccan' },
  { id: 51, name_arabic: 'الذاريات', name_latin: 'Adh-Dhariyat', translation_id: 'Angin Menerbangkan', total_verses: 60, revelation_type: 'meccan' },
  { id: 52, name_arabic: 'الطور', name_latin: 'At-Tur', translation_id: 'Bukit Tursina', total_verses: 49, revelation_type: 'meccan' },
  { id: 53, name_arabic: 'النجم', name_latin: 'An-Najm', translation_id: 'Bintang', total_verses: 62, revelation_type: 'meccan' },
  { id: 54, name_arabic: 'القمر', name_latin: 'Al-Qamar', translation_id: 'Bulan', total_verses: 55, revelation_type: 'meccan' },
  { id: 55, name_arabic: 'الرحمن', name_latin: 'Ar-Rahman', translation_id: 'Maha Pengasih', total_verses: 78, revelation_type: 'medinan' },
  { id: 56, name_arabic: 'الواقعة', name_latin: "Al-Waqi'ah", translation_id: 'Hari Kiamat', total_verses: 96, revelation_type: 'meccan' },
  { id: 57, name_arabic: 'الحديد', name_latin: 'Al-Hadid', translation_id: 'Besi', total_verses: 29, revelation_type: 'medinan' },
  { id: 58, name_arabic: 'المجادلة', name_latin: 'Al-Mujadila', translation_id: 'Gugatan', total_verses: 22, revelation_type: 'medinan' },
  { id: 59, name_arabic: 'الحشر', name_latin: 'Al-Hashr', translation_id: 'Pengusiran', total_verses: 24, revelation_type: 'medinan' },
  { id: 60, name_arabic: 'الممتحنة', name_latin: 'Al-Mumtahanah', translation_id: 'Wanita diuji', total_verses: 13, revelation_type: 'medinan' },
  { id: 61, name_arabic: 'الصف', name_latin: 'As-Saff', translation_id: 'Barisan', total_verses: 14, revelation_type: 'medinan' },
  { id: 62, name_arabic: 'الجمعة', name_latin: "Al-Jumu'ah", translation_id: 'Hari Jum\'at', total_verses: 11, revelation_type: 'medinan' },
  { id: 63, name_arabic: 'المنافقون', name_latin: 'Al-Munafiqun', translation_id: 'Orang Munafik', total_verses: 11, revelation_type: 'medinan' },
  { id: 64, name_arabic: 'التغابن', name_latin: 'At-Taghabun', translation_id: 'Kerugian', total_verses: 18, revelation_type: 'medinan' },
  { id: 65, name_arabic: 'الطلاق', name_latin: 'At-Talaq', translation_id: 'Talak', total_verses: 12, revelation_type: 'medinan' },
  { id: 66, name_arabic: 'التحريم', name_latin: 'At-Tahrim', translation_id: 'Pengharaman', total_verses: 12, revelation_type: 'medinan' },
  { id: 67, name_arabic: 'الملك', name_latin: 'Al-Mulk', translation_id: 'Kerajaan', total_verses: 30, revelation_type: 'meccan' },
  { id: 68, name_arabic: 'القلم', name_latin: 'Al-Qalam', translation_id: 'Pena', total_verses: 52, revelation_type: 'meccan' },
  { id: 69, name_arabic: 'Haqqah', name_latin: 'Al-Haqqah', translation_id: 'Hari Kiamat', total_verses: 52, revelation_type: 'meccan' },
  { id: 70, name_arabic: 'المعارج', name_latin: "Al-Ma'arij", translation_id: 'Tempat Naik', total_verses: 44, revelation_type: 'meccan' },
  { id: 71, name_arabic: 'نوح', name_latin: 'Nuh', translation_id: 'Nabi Nuh', total_verses: 28, revelation_type: 'meccan' },
  { id: 72, name_arabic: 'الجن', name_latin: 'Al-Jinn', translation_id: 'Jin', total_verses: 28, revelation_type: 'meccan' },
  { id: 73, name_arabic: 'المزمل', name_latin: 'Al-Muzzammil', translation_id: 'Berselimut', total_verses: 20, revelation_type: 'meccan' },
  { id: 74, name_arabic: 'المدثر', name_latin: 'Al-Muddaththir', translation_id: 'Berkemul', total_verses: 56, revelation_type: 'meccan' },
  { id: 75, name_arabic: 'القيامة', name_latin: 'Al-Qiyamah', translation_id: 'Hari Kiamat', total_verses: 40, revelation_type: 'meccan' },
  { id: 76, name_arabic: 'الإنسان', name_latin: 'Al-Insan', translation_id: 'Manusia', total_verses: 31, revelation_type: 'medinan' },
  { id: 77, name_arabic: 'المرسلات', name_latin: 'Al-Mursalat', translation_id: 'Malaikat diutus', total_verses: 50, revelation_type: 'meccan' },
  { id: 78, name_arabic: 'النبأ', name_latin: "An-Naba'", translation_id: 'Berita Besar', total_verses: 40, revelation_type: 'meccan' },
  { id: 79, name_arabic: 'النازعات', name_latin: "An-Nazi'at", translation_id: 'Malaikat mencabut', total_verses: 46, revelation_type: 'meccan' },
  { id: 80, name_arabic: 'عبس', name_latin: "'Abasa", translation_id: 'Bermuka Masam', total_verses: 42, revelation_type: 'meccan' },
  { id: 81, name_arabic: 'التكوير', name_latin: 'At-Takwir', translation_id: 'Menggulung', total_verses: 29, revelation_type: 'meccan' },
  { id: 82, name_arabic: 'الانفطار', name_latin: 'Al-Infitar', translation_id: 'Terbelah', total_verses: 19, revelation_type: 'meccan' },
  { id: 83, name_arabic: 'المطففين', name_latin: 'Al-Mutaffifin', translation_id: 'Orang Curang', total_verses: 36, revelation_type: 'meccan' },
  { id: 84, name_arabic: 'الانشقاق', name_latin: 'Al-Inshiqaq', translation_id: 'Terbelah', total_verses: 25, revelation_type: 'meccan' },
  { id: 85, name_arabic: 'البروج', name_latin: 'Al-Buruj', translation_id: 'Gugusan Bintang', total_verses: 22, revelation_type: 'meccan' },
  { id: 86, name_arabic: 'الطارق', name_latin: 'At-Tariq', translation_id: 'Yang Datang di Malam', total_verses: 17, revelation_type: 'meccan' },
  { id: 87, name_arabic: 'الأعلى', name_latin: "Al-A'la", translation_id: 'Maha Tinggi', total_verses: 19, revelation_type: 'meccan' },
  { id: 88, name_arabic: 'الغاشية', name_latin: 'Al-Ghashiyah', translation_id: 'Hari Pembalasan', total_verses: 26, revelation_type: 'meccan' },
  { id: 89, name_arabic: 'الفجر', name_latin: 'Al-Fajr', translation_id: 'Fajar', total_verses: 30, revelation_type: 'meccan' },
  { id: 90, name_arabic: 'البلد', name_latin: 'Al-Balad', translation_id: 'Negeri', total_verses: 20, revelation_type: 'meccan' },
  { id: 91, name_arabic: 'الشمس', name_latin: 'Ash-Shams', translation_id: 'Matahari', total_verses: 15, revelation_type: 'meccan' },
  { id: 92, name_arabic: 'الليل', name_latin: 'Al-Layl', translation_id: 'Malam', total_verses: 21, revelation_type: 'meccan' },
  { id: 93, name_arabic: 'الضحى', name_latin: 'Ad-Duha', translation_id: 'Waktu Dhuha', total_verses: 11, revelation_type: 'meccan' },
  { id: 94, name_arabic: 'الشرح', name_latin: 'Ash-Sharh', translation_id: 'Kelapangan', total_verses: 8, revelation_type: 'meccan' },
  { id: 95, name_arabic: 'التين', name_latin: 'At-Tin', translation_id: 'Buah Tin', total_verses: 8, revelation_type: 'meccan' },
  { id: 96, name_arabic: 'العلق', name_latin: "Al-'Alaq", translation_id: 'Segumpal Darah', total_verses: 19, revelation_type: 'meccan' },
  { id: 97, name_arabic: 'القدر', name_latin: 'Al-Qadr', translation_id: 'Kemuliaan', total_verses: 5, revelation_type: 'meccan' },
  { id: 98, name_arabic: 'البينة', name_latin: 'Al-Bayyinah', translation_id: 'Bukti Nyata', total_verses: 8, revelation_type: 'medinan' },
  { id: 99, name_arabic: 'Zalzalah', name_latin: 'Az-Zalzalah', translation_id: 'Kegoncangan', total_verses: 8, revelation_type: 'medinan' },
  { id: 100, name_arabic: 'العاديات', name_latin: "Al-'Adiyat", translation_id: 'Kuda Kencang', total_verses: 11, revelation_type: 'meccan' },
  { id: 101, name_arabic: 'القارعة', name_latin: "Al-Qari'ah", translation_id: 'Hari Kiamat', total_verses: 11, revelation_type: 'meccan' },
  { id: 102, name_arabic: 'التكاثر', name_latin: 'At-Takathur', translation_id: 'Bermegah-megahan', total_verses: 8, revelation_type: 'meccan' },
  { id: 103, name_arabic: 'العصر', name_latin: "Al-'Asr", translation_id: 'Masa', total_verses: 3, revelation_type: 'meccan' },
  { id: 104, name_arabic: 'الهمزة', name_latin: 'Al-Humazah', translation_id: 'Pengumpat', total_verses: 9, revelation_type: 'meccan' },
  { id: 105, name_arabic: 'الفيل', name_latin: 'Al-Fil', translation_id: 'Gajah', total_verses: 5, revelation_type: 'meccan' },
  { id: 106, name_arabic: 'قريش', name_latin: 'Quraysh', translation_id: 'Suku Quraisy', total_verses: 4, revelation_type: 'meccan' },
  { id: 107, name_arabic: 'الماعون', name_latin: "Al-Ma'un", translation_id: 'Barang Berguna', total_verses: 7, revelation_type: 'meccan' },
  { id: 108, name_arabic: 'الكوثر', name_latin: 'Al-Kawthar', translation_id: 'Nikmat Berlimpah', total_verses: 3, revelation_type: 'meccan' },
  { id: 109, name_arabic: 'الكافرون', name_latin: 'Al-Kafirun', translation_id: 'Orang Kafir', total_verses: 6, revelation_type: 'meccan' },
  { id: 110, name_arabic: 'النصر', name_latin: 'An-Nasr', translation_id: 'Pertolongan', total_verses: 3, revelation_type: 'medinan' },
  { id: 111, name_arabic: 'المسد', name_latin: 'Al-Masad', translation_id: 'Gejolak Api', total_verses: 5, revelation_type: 'meccan' },
  { id: 112, name_arabic: 'الإخلاص', name_latin: 'Al-Ikhlas', translation_id: 'Ikhlas', total_verses: 4, revelation_type: 'meccan' },
  { id: 113, name_arabic: 'الفلق', name_latin: 'Al-Falaq', translation_id: 'Waktu Subuh', total_verses: 5, revelation_type: 'meccan' },
  { id: 114, name_arabic: 'الناس', name_latin: 'An-Nas', translation_id: 'Manusia', total_verses: 6, revelation_type: 'meccan' },
];
